### ISSUE TITLE
As a User, I want to be able to visually distinguish between the logout button and the other buttons in the navbar.

### ISSUE THREAD

**Issue by ksennr** [sopra-fs22-group-03/sopra-fs22-group-03-client#35]

**Comment by ksennr** [comment]
Visually separate the logout button
- the coloring should be red, red is signalling that the functionality differs from the other buttons
- the design should not break the other elements views (e.g. borderradius)
- the button should be physically separated from the other buttons

**Comment by nmamie** [comment]
a28a32cbcb9180fde6700a8901f0501c15975c25
